### ISSUE TITLE
Want format control

### ISSUE THREAD

**Issue by FaroutYLq** [FaroutYLq/saltax#27]
**Describe the feature**
_A clear and concise description of what the feature is._
Something like black should work.

**Expected behavior**
_Make an imaginary example of how the feature would work._
Hopefully auto PR?

**Proposed implementation**
_Any rough idea how would you implement this feature?_ 

**Potential risk**
_Will there be any risk after adding this feature?_

All _italic_ comments can be removed from this template.

**Comment by FaroutYLq** [comment]
https://github.com/reviewdog/reviewdog this is also nice to have

**Comment by FaroutYLq** [comment]
Should try this: https://github.com/XENONnT/straxen/pull/1240

**Comment by dachengx** [comment]
I highly recommend pre-commit for a developing repo. See detailed reason at: https://github.com/XENONnT/alea/pull/78.
